# Generated by Django 2.1 on 2023-06-03 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='pid1',
            new_name='pid',
        ),
    ]
