# Generated by Django 2.1 on 2023-06-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230603_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='cname',
            new_name='cid',
        ),
    ]
